#!/bin/bash
# Test the Skill Guardian system with Tracking and Auto-Spawning

echo "🛡️  Testing Skill Guardian System + Tracking..."
echo ""

# Build
echo "Building..."
go build -o fight-cli fight-cli.go

if [ $? -ne 0 ]; then
    echo "❌ Build failed!"
    exit 1
fi

echo "✅ Build successful!"
echo ""

# Run basic tests
echo "Running tests..."
go test -run "TestCharacterCreation|TestSkills" -v

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "🎮 NEW FEATURES READY TO TEST!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✨ TRACKING SKILL"
echo "  • Learn from a Skill Guardian"
echo "  • See all monsters at a location"
echo "  • Choose which monster to fight"
echo "  • Identify guardians with 🎯 tag"
echo ""
echo "🎯 AUTOMATIC GUARDIAN SPAWNING"
echo "  • Guardians spawn based on location level"
echo "  • Level 10-29:  1 guardian"
echo "  • Level 30-99:  2 guardians"
echo "  • Level 100+:   3 guardians"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📋 TESTING STEPS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "1. START GAME"
echo "   ./fight-cli"
echo ""
echo "2. VIEW GUARDIAN SPAWNS"
echo "   • Select option 4 (Print Discovered Locations)"
echo "   • Look for guardian spawn messages:"
echo "     🎯 Spawned Fire Elemental (Lv48) guarding Fireball at Hunters Lodge"
echo "   • Check guardian counts per location"
echo ""
echo "3. TEST WITHOUT TRACKING"
echo "   • Create/Load character"
echo "   • Select option 3 (Hunt)"
echo "   • Choose location (e.g., Training Hall)"
echo "   • Enter hunt count (e.g., 1)"
echo "   • Random monster selected (original behavior)"
echo ""
echo "4. LEARN TRACKING SKILL"
echo "   • Hunt at location with guardians"
echo "   • Defeat a Skill Guardian"
echo "   • Choose to absorb Tracking skill (if available)"
echo "   • Or keep hunting until you find Tracking guardian"
echo ""
echo "5. TEST WITH TRACKING"
echo "   • Select option 3 (Hunt)"
echo "   • Choose location"
echo "   • Enter hunt count"
echo "   • See monster selection menu:"
echo "     🔍 TRACKING ACTIVE - Choose your target:"
echo "     1. slime (Lv12) - HP:6/6"
echo "     2. goblin (Lv15) - HP:8/8"
echo "     3. Fire Elemental (Lv18) - HP:24/24 🎯 [SKILL GUARDIAN]"
echo "   • Choose a number (1-20) or 0 for random"
echo "   • Verify correct monster is fought"
echo ""
echo "6. TEST GUARDIAN FIGHTS"
echo "   • With Tracking, choose a guardian"
echo "   • Verify tougher fight (2x HP, +2 rolls)"
echo "   • On victory, get skill choice:"
echo "     1 = Absorb skill immediately"
echo "     2 = Take skill scroll"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "🔍 EXPECTED RESULTS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "✓ Training Hall (LvMax 20) → 0 guardians"
echo "✓ Forest (LvMax 20) → 0 guardians"
echo "✓ Hunters Lodge (LvMax 50) → 1 guardian"
echo "✓ Forest Ruins (LvMax 100) → 2 guardians"
echo "✓ Ancient Dungeon (LvMax 200) → 3 guardians"
echo ""
echo "✓ Without Tracking: Random selection"
echo "✓ With Tracking: Selection menu appears"
echo "✓ Guardian tag visible in both views"
echo "✓ Can target specific monsters"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📚 DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Full docs available:"
echo "  • TRACKING_AND_GUARDIAN_SPAWNING.md - Complete guide"
echo "  • QUICK_REFERENCE.txt - Quick lookup"
echo "  • SKILL_GUARDIAN_SYSTEM.md - Guardian mechanics"
echo ""
echo "Read QUICK_REFERENCE.txt for fast tips!"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "🚀 Ready to play!"
echo "═══════════════════════════════════════════════════════════"
